### ISSUE TITLE
Also add schemas for validation process?

### ISSUE THREAD

**Issue by fabolhak** [boschrexroth/json-schema#6]
I was wondering if it is possible to add the schemas for the validation process here somewhere? Then it would be easier to reference them in the required json files for the validation process.

Currently, they only seem to be available in the [artifacts.zip](https://github.com/boschrexroth/ctrlx-automation-sdk/blob/main/doc/artifacts.zip) file.

Missing schemas: 

* `portlist-description_schema.json`
* `slotplug-description_schema.json`
* `unixsocket-description_schema.json`

Would be happy to create a PR if you let me know where to put them.

**Comment by mapero** [comment]
Hi @fabolhak 

I have added the missing schemas to the list, you can find them here:
https://json-schema.boschrexroth.com/ctrlx-automation/ctrlx-os/#validation-schemas

https://json-schema.boschrexroth.com/ctrlx-automation/ctrlx-os/apps/validation/unixsocket-description/unixsocket-description.v1.schema.json
https://json-schema.boschrexroth.com/ctrlx-automation/ctrlx-os/apps/validation/slotplug-description/slotplug-description.v1.schema.json
https://json-schema.boschrexroth.com/ctrlx-automation/ctrlx-os/apps/validation/portlist-description/portlist-description.v1.schema.json

Thanks for your suggestion.
